version = 0.1
[default.deploy.parameters]
stack_name = "RecomendAiStack"
resolve_s3 = true
s3_prefix = "RecomendAiStack"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"recomendai-bucket-2023\" AcmCertificateArn=\"\" AlternateDomainName=\"\""
image_repositories = []
